name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "**/package-lock.json"

    # Charger les variables dâ€™environnement depuis le fichier .env
    - name: Load environment variables
      run: |
        set -a  # Active l'export automatique des variables
        source .env  # Charge les variables depuis .env
        set +a  # DÃ©sactive lâ€™export automatique aprÃ¨s chargement

    # DÃ©marrer toutes les applications listÃ©es dans le .env
    - name: Start all applications
      run: |
        echo "Liste des applications: $APP_LIST"
        IFS=',' read -ra APPS <<< "$APP_LIST"
        
        for APP_NAME in "${APPS[@]}"; do
          # Construire les noms de variables
          APP_VAR_PATH="${APP_NAME^^}_PATH"  
          APP_PATH="${!APP_VAR_PATH}"

          
          # Afficher le nom de lâ€™application et la date
          echo "-----------------------------------"
          echo "ðŸš€ DÃ©marrage de l'application : $APP_NAME"
          echo "ðŸ“… Date : $(date)"
          echo "-----------------------------------"


          cd "$APP_PATH"

          npm ci
          npm run build --if-present
          npm start & echo $! > "$APP_PATH/app.pid"
        done
